import Head from 'next/head'
import Header from '@/src/components/header/header'
import Footer from '@/src/components/footer/footer'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
       <div>
       <section>
            <h2>Nosso projeto no Figma</h2>                
            <img src="exemplo.png" alt="imagem figma" height="100%" width="100%"/>
        </section>
      <Footer/>
        </div>

    </>
  )
}