import Head from 'next/head'
import Header from '@/src/components/header/header'
import Footer from '@/src/components/footer/footer'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
       <div>
        
        <section>
            <h2>Nossa ideia</h2>
            <p>

                Tendo em vista as solicitações do projeto e as características do atual chatbot da Porto, pensamos em
                uma otimização, para que as informações sejam completas, evitando retornos e
                “mensagens de erros”, ou seja, um apontamento de que o chatbot não entendeu o que foi passado. Assim,
                podemos melhorar essas questões com itens práticos;
            </p>
            <p/>
            <ul>
                <li>Primeiro a criação de um banco de dados, que se trata de um armazenamento das informações do veículo
                    e
                    pode ser atualizado diretamente pelo cliente sobre as características do veículo, que incluem
                    mudanças
                    físicas, tipo e peso de carga (se houver);</li>
                <li>Um alerta com funcionalidade periódica (de três em três meses, por exemplo) que, no próprio
                    aplicativo ou por mensagem de texto, dará um aviso ao cliente a respeito da necessidade da
                    atualização das informações referentes às características do veículo;</li>
                <li>Utilização de reconhecimento de voz para maior acessibilidade, para que algumas pessoas tenham maior
                    facilidade no momento de um acidente;</li>
                <li>Incremento de reconhecimento de imagens por uma Inteligencia Artificial, para auxiliar com o recurso
                    visual qual o melhor modal.</li>
            </ul>
        
            <p>
                Em resumo, o objetivo é criar um chatbot que possua um modelo prático, de fácil entendimento e que todas
                informações necessárias e importantes são geradas no chatbot sem a necessidade da interferência humana,
                para maior facilidade e eficiência ter uma integração de reconhecimento de imagens por IA, para que seja
                possível diminuir o tempo da escolha do modal adequado para cada situação, aumentando a automação do
                serviço.
            </p>

        </section>
      <Footer/>
        </div>

    </>
  )
}