import Head from 'next/head'
import Header from '@/src/components/header/header'
import Footer from '@/src/components/footer/footer'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
       <div>
        <div> 
        <section>
            <h2>Situação...</h2>
            <p>
                Atualmente, o processo de escolha do modal para atendimento de veículos pesados gera esforço operacional
                (humano) para realizar o acionamento do melhor modal (tipo de guincho). Ainda assim não é possível ter
                um prestação de serviços completamente eficiente, visto que entre 10 a 15% dos atendimentos necessitam
                retrabalhos (outro tipo de guincho requerido pelo prestador já no local).
            </p>
            <p>
                Ao testar chatbot para um melhor compreendimento do problema, constatamos certas questões
                de otimização e facilidade - ou falta dela - na utilização do chatbot da Porto. Identificamos que
                algumas perguntas são redundantes e as
                informações não são passadas de forma clara, faltando informações para o trabalho ser mais eficiente.
              </p>
          </section>
        </div>
      <Footer/>
        </div>

    </>
  )
}
